### ISSUE TITLE
Submodules/diff-gaussian-rasterization has build errors.

### ISSUE THREAD

**Issue by faster-developer** [ubc-vision/3dgs-mcmc#1]
I can't get this submodule to build. With regular Gaussian splatting it is no problem, but I'm running into C++ compile issues. What could be the problem?

**Comment by henrypearce4D** [comment]
I am also getting issues. I'm running windows but with the original repo it is fine.

I had errors of missing compute_relocation so added the line in
`submodules\diff_gaussian_rasterization\diff_gaussian_rasterization\__init__.py`
```
from ._C import compute_relocation
```



And then created
`submodules\diff_gaussian_rasterization\compute_relocation.cpp`
```
#include <torch/extension.h>

// Example definition of compute_relocation
torch::Tensor compute_relocation(torch::Tensor input) {
    // Dummy implementation: just return the input tensor
    return input;
}
```

Then added the line in
`submodules\diff_gaussian_rasterization\ext.cpp`

```
#include "compute_relocation.cpp"  // Include your compute_relocation definition
```

I then ran into problems with things missing because of using python 3.7.

**Comment by faster-developer** [comment]
> I then ran into problems with things missing because of using python 3.7.
If you're using Conda you can rebuild the project with a different Python version: 
```
conda activate existing_env
conda install python=3.x.x
```

**Comment by faster-developer** [comment]
When compiling I still get this error:

```
      C:\Users\xxx\gsplat\3dgs-mcmc\submodules\diff-gaussian-rasterization\cuda_rasterizer\utils.cu(29): error: calling a __host__ function("double  ::sqrt<int, (int)0> (T1)") from a __global__ function("compute_relocation") is not allowed
      C:\Users\xxx\gsplat\3dgs-mcmc\submodules\diff-gaussian-rasterization\cuda_rasterizer\utils.cu(29): error: identifier "sqrt<int, (int)0> " is undefined in device code
```

**Comment by shakibakh** [comment]
The code has only been tested on Ubuntu 20.04. I updated the how to install section in readme with the correct package versions.
