### ISSUE TITLE
Question about relocate_gs()

### ISSUE THREAD

**Issue by wangwang-xyz** [ubc-vision/3dgs-mcmc#21]
It seems only the optimizer parameters of the alive gaussians that are sampled are reset, while the optimizer parameters of the dead gaussians remain unchanged. May I ask the reason for this？

**Comment by shakibakh** [comment]
Thank you for your interest in our work!
We found that this gives the best result. Alive gaussians' optimizer's values are reset so they do more exploitation in the vicinity of the found "local minima", while the new gaussians' explore starting from that point. This is also stated in the paper, Section 3.4 - Implementation:

>  Finally, as we rely on the Adam optimizer, moment statistics should also be adjusted. We reset the moment statistics for the target Gaussian (the original one that is cloned) so that it is biased to stay stationary, while for the new ones
(source) we retain the moment statistics to encourage exploration. (This is because ‘dead’ (source) Gaussians are dominated by the noise term in (7), and the moment statistics are hence appropriate to foster exploration).

**Comment by shakibakh** [comment]
Closing the issue. Please feel free to reopen it if you have any further questions or concerns.
